// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

/**
 * 
 */
namespace CommonToolTags
{
	//UI 状态
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Main);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_MainMenu);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Simulate_Maintenance);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Edit);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Inspection);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_WeatherSimulation);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DigitalArchives);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Roam);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Highlights);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Null);

	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DeviceState_Ledger);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DeviceState_OperatingData);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DeviceState_History);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DeviceState_Document);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DeviceState_Null);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DeviceState_Disassemble);
	
	//actor筛选
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Actor_Type_Null);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Actor_Type_Device);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Actor_Type_Build);

	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DigitalArchives_Design);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DigitalArchives_Build);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DigitalArchives_CheckAndAccept);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DigitalArchives_Operation);
	
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DialogState_Null);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DialogState_Set);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DialogState_Weather);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DialogState_EditorOption);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DialogState_EditorAttribute);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DialogState_MarkType);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DialogState_Introduction);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DialogState_Measurement);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DialogState_WiringDiagram);

	//用户操作模式状态
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UserState_Panorama); //全景
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UserState_FirstPerson); //第一人称
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UserState_ThirdPerson); //第三人称
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UserState_Focus); //聚焦
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UserState_Free); //自由
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UserState_Null);

	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AlignSpace_Local);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AlignSpace_World);

	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TransformMode_Translation);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TransformMode_Rotation);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TransformMode_Scale);

	//约束轴
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConstraintAxis_X);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConstraintAxis_Y);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConstraintAxis_Z);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConstraintAxis_XY);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConstraintAxis_XZ);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConstraintAxis_YZ);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConstraintAxis_XYZ);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConstraintAxis_Screen);

	//PointerInteractionSource
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PointerInteractionSource_World);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PointerInteractionSource_MouseCursor);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PointerInteractionSource_ScreenCenter);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PointerInteractionSource_Custom);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PointerInteractionSource_Overlap);

	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Edit_Mark);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Edit_Device);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Edit_Pawn);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Edit_Scene);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Edit_Asset);
	
	//COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_Folder);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_Image);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_Datasmith);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_FBX);

	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MeshStatus_Move);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MeshStatus_Replace);
	
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FolderStatus_MeshModuleResource);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FolderStatus_Drag);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FolderStatus_Function);

	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_Folder);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_Point);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_Line);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_Surface);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_Tile);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_Map);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_Mesh);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_Circle);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_Arrow);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_Decal);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_Projection);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_WidgetProjection);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_PointCloud);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FileType_Plant);
	
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VisitStatus_Local);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(VisitStatus_Network);
	
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FunctionType_Default);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FunctionType_Point);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FunctionType_Line);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FunctionType_Surface);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FunctionType_Circle);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FunctionType_Arrow);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FunctionType_Decal);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FunctionType_Projection);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FunctionType_WidgetProjection);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FunctionType_PointCloud);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FunctionType_Plant);
	
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EditStatus_Current);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EditStatus_Previous);
	
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EditType_Normal);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EditType_Normal_Dynamic);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EditType_Check);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EditType_Select);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EditType_Option);
	
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EMessageType_Normal);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EMessageType_Waning);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EMessageType_Error);

	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(E3DUI_Type_DeviceInfo);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(E3DUI_Type_DeviceInfoSelect);
	COMMONTOOL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(E3DUI_Type_TrainStationMarking);
}

class COMMONTOOL_API CommonToolTag
{
public:
	CommonToolTag();
	~CommonToolTag();
};
